# Ruda configuration file
# 
# See official documentation for more information:
# (todo add link to documentation)

[project]
name = "{{name}}"
version = "{{version}}"
author = "{{author}}"
kind = "{{kind}}"
license = "MIT"
runtime = "latest"
description = "description"
3rdparty = "allow" # "allow" | "std" | "sandboxed" | "deny"

[dependencies]
binaries = []

[profile.default]
