[package]
name = "rudadb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
ratatui = { version = "0.23.0", features = ["all-widgets"] }
runtime = { path = "../vm/runtime" }
crossterm = "*"